export const environment = {
  production: false,
  API_KEY: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2NzYyZTI0MzhjZDQyZDAyMzcyZjI1ZTU3MDFiN2M0ZSIsIm5iZiI6MTcyNzcxNzMxMC45ODU1NzYsInN1YiI6IjY1NTY1NDUyN2YwNTQwMDBlMmFmMzQ3MyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.eGMEsf8EC5Hn1gLCqHoUmqsVn0j-G5RlWjoBq5UWZsc'
};
